name: Sync Distributed Folder

on:
  #push:
  #  branches:
  #    - 'main'
  #  paths:
  #    - 'torch/distributed/**'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/scripts/sync_distributed_folder_prototype.sh'
      - '.github/workflows/sync_distributed_folder_prototype.yml'

env:
  WITH_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .github/scripts/sync_distributed_folder_prototype.sh
